import React from "react"
import { FileDown, MessageCircle, BarChart3, Clock, Package, AlertTriangle } from "lucide-react"
import jsPDF from "jspdf"
import autoTable from "jspdf-autotable"

function Reports({ products = [], salesLog = [] }) {
  // ==========================================
  // CORE & STRONG ANALYTICS FEATURES EXTRACTED
  // ==========================================
  
  // 1. Single-pass stock aggregation loop (Highly Performant)
  const totalProducts = products.length
  const lowStock = []
  const outOfStock = []

  for (let i = 0; i < products.length; i++) {
    const item = products[i]
    const stockNum = Number(item.stock || 0)
    // Dynamic matching using your standard threshold or fallback to 5
    const threshold = Number(item.lowStockThreshold || 5) 

    if (stockNum === 0) {
      outOfStock.push(item)
    } else if (stockNum <= threshold) {
      lowStock.push(item)
    }
  }

  // Get today's date structure for analytical matching
  const todayString = new Date().toLocaleDateString()

  // 2. Exact Filter for Today's Transactions
  const todaySales = salesLog.filter(sale => sale.date && sale.date.includes(todayString))

  // 3. Multi-Metric Accumulator (Grabs total revenue and processes Top-Selling products in one pass)
  const { todayRevenue, topProducts } = todaySales.reduce((acc, s) => {
    const qty = Number(s.quantity || 0)
    const price = Number(s.price || 0)
    const rev = qty * price

    // Accumulate running financial revenue
    acc.todayRevenue += rev

    // Build unique tracking map for top-selling items metrics
    const pId = s.productId || s.name
    if (!acc.processedSales[pId]) {
      acc.processedSales[pId] = { name: s.name, qty: 0, revenue: 0 }
    }
    acc.processedSales[pId].qty += qty
    acc.processedSales[pId].revenue += rev

    return acc;
  }, { todayRevenue: 0, processedSales: {}, topProducts: [] })

  // Finalize processing for the Top 3 highest grossing performers today
  const computedTopProducts = Object.values(topProducts.length ? {} : todaySales.reduce((acc, s) => {
    const pId = s.productId || s.name
    if (!acc[pId]) acc[pId] = { name: s.name, qty: 0, revenue: 0 }
    acc[pId].qty += Number(s.quantity || 0)
    acc[pId].revenue += Number(s.quantity || 0) * Number(s.price || 0)
    return acc
  }, {})).sort((a, b) => b.revenue - a.revenue).slice(0, 3)

  // ==========================================
  // COMPATIBLE WHATSAPP ENGINE STRING BUILDER
  // ==========================================
  const reportText = `📊 *Inventory Report (Today - ${todayString})*

📦 Total Products: ${totalProducts}
💰 Today's Sales: ₦${todayRevenue.toLocaleString()}

⚠️ Low Stock Items: ${lowStock.length}
❌ Out of Stock: ${outOfStock.length}

*Top Performers Today:*
${computedTopProducts.length 
  ? computedTopProducts.map((p, i) => `${i + 1}. ${p.name} (₦${p.revenue.toLocaleString()})`).join("\n")
  : "• No performance metrics yet."
}

*Sales Made Today:*
${todaySales.length 
  ? todaySales.map(sale => `• ${sale.name} → ${sale.quantity} sold at ${sale.date.split(',')[1] || sale.date}`).join("\n")
  : "• No sales made yet today."
}

Generated by Inventory App`

  // ==========================================
  // WEB SERVICE ACTIONS & TRIGGERS
  // ==========================================
  function shareToWhatsApp() {
    const text = encodeURIComponent(reportText)
    window.open(`https://wa.me/?text=${text}`, "_blank")
  }

  function downloadReportText() {
    const blob = new Blob([reportText], { type: "text/plain;charset=utf-8" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `report-${new Date().toISOString().slice(0, 10)}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  function downloadPDF() {
    const doc = new jsPDF()

    // Header Branding Section
    doc.setFont("helvetica", "bold")
    doc.setFontSize(20)
    doc.text("Inventory App", 14, 20)

    doc.setFont("helvetica", "normal")
    doc.setFontSize(14)
    doc.text("Inventory Report", 14, 28)

    doc.setFontSize(10)
    doc.text(`Date Range: ${todayString}`, 14, 36)
    doc.text(`Generated Date + Time: ${new Date().toLocaleString()}`, 14, 42)

    // Quick Summary Table (What we have & what we sold)
    autoTable(doc, {
      startY: 50,
      head: [["Metric", "Value"]],
      body: [
        ["Total Products in App", totalProducts],
        ["Today's Sales Revenue", "NGN" + todayRevenue.toLocaleString()],
        ["Low Stock Items", lowStock.length],
        ["Out of Stock Items", outOfStock.length]
      ],
      theme: "grid",
      headStyles: { fillColor: [15, 23, 42] } // Polished slate aesthetic palette
    })

    // Today's Sales Breakdown Table
    doc.setFont("helvetica", "bold")
    doc.setFontSize(12)
    doc.text("Sales Made Today", 14, doc.lastAutoTable.finalY + 12)

    const tableRows = todaySales.map(sale => [
      sale.name,
      sale.quantity,
      "NGN" + (Number(sale.price) * Number(sale.quantity)).toLocaleString(),
      sale.date.split(",")[1] || sale.date
    ])

    autoTable(doc, {
      startY: doc.lastAutoTable.finalY + 16,
      head: [["Product Name", "Quantity Sold", "Total Price", "Time of Sale"]],
      body: tableRows.length ? tableRows : [["No sales recorded today.", "-", "-", "-"]],
      theme: "striped",
      headStyles: { fillColor: [79, 70, 229] } // Premium brand accent indicator color
    })

    doc.save(`Inventory_Report_${todayString}.pdf`)
  }

  return (
    <div className="reports-page">
      
      {/* HEADER ROW */}
      <div className="reports-header">
        <div className="reports-title">
          <BarChart3 size={22} className="reports-icon-accent" />
          <div>
            <h2>Simple Shop Report</h2>
            <p>Today's stock levels and sales tracking</p>
          </div>
        </div>

        <div className="reports-actions">
          <button onClick={downloadPDF} className="download-btn">
            <FileDown size={16} /> PDF Export
          </button>
          <button onClick={downloadReportText} className="download-btn secondary">
            TXT Download
          </button>
          <button onClick={shareToWhatsApp} className="whatsapp-btn">
            <MessageCircle size={16} /> WhatsApp Share
          </button>
        </div>
      </div>

      {/* DASHBOARD PREVIEW SHELL */}
      <div className="report-card">
        
        {/* FINANCIAL SUMMARY BOXES */}
        <div className="report-grid">
          <div className="report-box report-summary-box">
            <div className="report-box-meta">
              <Package size={16} />
              <p>Total Products We Have</p>
            </div>
            <h2>{totalProducts} Items</h2>
          </div>

          <div className="report-box report-summary-box">
            <div className="report-box-meta report-box-meta-accent">
              <Clock size={16} />
              <p>Sales Revenue Made Today</p>
            </div>
            <h2 className="report-value-highlight">₦{todayRevenue.toLocaleString()}</h2>
          </div>
        </div>

        {/* ANALYTICS SPLIT SECTIONS */}
        <div className="report-details-split-grid">
          
          {/* TRACKING TIMELINE BLOCK */}
          <div className="report-section report-section-panel">
            <div className="section-title-wrapper">
              <Clock size={16} />
              <h3>Sales Made Today & Time Occurred</h3>
            </div>
            <div className="nested-scrolling-alert-list">
              {todaySales.length > 0 ? (
                todaySales.map((sale, i) => (
                  <div key={i} className="report-item report-item-row">
                    <span>{sale.name} ({sale.quantity} sold)</span>
                    <strong>{sale.date.split(',')[1] || sale.date}</strong>
                  </div>
                ))
              ) : (
                <p className="report-empty-text">No sales have been recorded yet today.</p>
              )}
            </div>
          </div>

          {/* DYNAMIC ALERT TRACKERS BLOCK */}
          <div className="report-section report-section-panel report-section-column">
            
            {/* Stock Levels Status Indicators */}
            <div className="status-panel">
              <h3>Stock Alerts</h3>
              <div className="report-status-summary-row">
                <div className="status-micro-pill red-pill">
                  <span>Out of Stock</span>
                  <strong>{outOfStock.length} items</strong>
                </div>
                <div className="status-micro-pill amber-pill">
                  <span>Low Stock</span>
                  <strong>{lowStock.length} items</strong>
                </div>
              </div>
            </div>

            {/* NEW ADDED CORE FEATURE: Premium Ranking Block for Top Items */}
            {computedTopProducts.length > 0 && (
              <div className="status-panel">
                <h3>Today's Top High-Grossing Products</h3>
                <div className="top-products-list">
                  {computedTopProducts.map((p, idx) => (
                    <div key={idx} className="top-product-item">
                      <span className="top-product-rank">{idx + 1}</span>
                      <span className="top-product-name">{p.name}</span>
                      <span className="top-product-value">₦{p.revenue.toLocaleString()}</span>
                    </div>
                  ))}
                </div>
              </div>
            )}

          </div>

        </div>

      </div>
    </div>
  )
}

export default Reports