import React from "react"
import { FileDown, MessageCircle, BarChart3, Clock, Package, AlertTriangle } from "lucide-react"
import jsPDF from "jspdf"
import autoTable from "jspdf-autotable"

function Reports({ products = [], salesLog = [] }) {
  // ==========================================
  // CORE & STRONG ANALYTICS FEATURES EXTRACTED
  // ==========================================
  
  const totalProducts = products.length
  const lowStock = []
  const outOfStock = []
  const expiredProducts = []
  const expiringSoonProducts = []

  // Enhanced Single-pass stock & expiration aggregation loop
  for (let i = 0; i < products.length; i++) {
    const item = products[i]
    const stockNum = Number(item.stock || 0)
    const threshold = Number(item.lowStockThreshold || item.reorderLevel || 5) 

    // 1. Stock Evaluation
    if (stockNum === 0) {
      outOfStock.push(item)
    } else if (stockNum <= threshold) {
      lowStock.push(item)
    }

    // 2. Expiration Evaluation (with structural variants alignment fallback)
    let checkExpiryDate = item.expiryDate
    if (Array.isArray(item.variants) && item.variants.length > 0) {
      checkExpiryDate = item.variants[0]?.expiryDate
    }

    if (checkExpiryDate && checkExpiryDate !== "N/A" && checkExpiryDate !== "") {
      const expiry = new Date(checkExpiryDate)
      const today = new Date()
      today.setHours(0, 0, 0, 0)
      expiry.setHours(0, 0, 0, 0)
      const daysRemaining = Math.round((expiry - today) / (24 * 60 * 60 * 1000))

      if (daysRemaining < 0) {
        expiredProducts.push(item)
      } else if (daysRemaining <= 90) {
        expiringSoonProducts.push(item)
      }
    }
  }

  // Get today's date structure for analytical matching
  const todayString = new Date().toLocaleDateString()

  // Exact Filter for Today's Transactions that EXCLUDES product creation logs
  const todaySales = salesLog.filter(sale => 
    sale.date && 
    sale.date.includes(todayString) && 
    sale.action !== "CREATE"
  )

  // Multi-Metric Accumulator (Grabs total revenue using the correct sold quantity fallback)
  const { todayRevenue } = todaySales.reduce((acc, s) => {
    // FIX: Parentheses added to resolve mixed logical operator precedence rules
    const qty = Number((s.sellQuantity ?? s.quantity) || 0)
    const price = Number(s.price || 0)
    acc.todayRevenue += (qty * price)
    return acc
  }, { todayRevenue: 0 })

  // Finalize processing for the Top 3 highest grossing performers today using correct sold quantities
  const computedTopProducts = Object.values(todaySales.reduce((acc, s) => {
    const pId = s.productId || s.name
    // FIX: Parentheses added to resolve mixed logical operator precedence rules
    const qtySold = Number((s.sellQuantity ?? s.quantity) || 0)
    
    if (!acc[pId]) acc[pId] = { name: s.name, qty: 0, revenue: 0 }
    acc[pId].qty += qtySold
    acc[pId].revenue += qtySold * Number(s.price || 0)
    return acc
  }, {})).sort((a, b) => b.revenue - a.revenue).slice(0, 3)

  // ==========================================
  // COMPATIBLE WHATSAPP ENGINE STRING BUILDER
  // ==========================================
  const reportText = `📊 *Tipia Demo - Inventory Report (${todayString})*

📦 Total Products: ${totalProducts}
💰 Today's Sales: ₦${todayRevenue.toLocaleString()}

⚠️ Low Stock Items: ${lowStock.length}
❌ Out of Stock: ${outOfStock.length}
⏳ Expiring Soon (≤90 days): ${expiringSoonProducts.length}
🚨 Expired Products: ${expiredProducts.length}

*Stock Alerts:*
${lowStock.length ? `• Low Stock: ${lowStock.map(p => `${p.name} (${p.stock} left)`).join(", ")}` : "• No low stock items."}
${outOfStock.length ? `• Out of Stock: ${outOfStock.map(p => p.name).join(", ")}` : "• No out of stock items."}
${expiringSoonProducts.length ? `• Expiring Soon: ${expiringSoonProducts.map(p => p.name).join(", ")}` : "• No near-expiry items."}
${expiredProducts.length ? `• Expired: ${expiredProducts.map(p => p.name).join(", ")}` : "• No expired items."}

*Top Performers Today:*
${computedTopProducts.length 
  ? computedTopProducts.map((p, i) => `${i + 1}. ${p.name} (₦${p.revenue.toLocaleString()})`).join("\n")
  : "• No performance metrics yet."
}

Generated by Tipia`

  // ==========================================
  // WEB SERVICE ACTIONS & TRIGGERS
  // ==========================================
  function shareToWhatsApp() {
    const text = encodeURIComponent(reportText)
    window.open(`https://wa.me/?text=${text}`, "_blank")
  }

  function downloadReportText() {
    const blob = new Blob([reportText], { type: "text/plain;charset=utf-8" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `tipia-report-${new Date().toISOString().slice(0, 10)}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  function downloadPDF() {
    const doc = new jsPDF()

    // Header Branding Section
    doc.setFont("helvetica", "bold")
    doc.setFontSize(22)
    doc.text("Tipia Demo", 14, 20)

    doc.setFont("helvetica", "normal")
    doc.setFontSize(14)
    doc.text("Comprehensive Inventory & Risk Analytics Report", 14, 28)

    doc.setFontSize(10)
    doc.text(`Date Range: ${todayString}`, 14, 36)
    doc.text(`Generated Date + Time: ${new Date().toLocaleString()}`, 14, 42)

    // Quick Summary Table (Expanded with expiration layers)
    autoTable(doc, {
      startY: 48,
      head: [["Core Operational Metric", "Current Metric Value Mapping"]],
      body: [
        ["Total Active Products Tracked", totalProducts],
        ["Today's Realized Sales Revenue", "NGN " + todayRevenue.toLocaleString()],
        ["Low Stock Items (Under Threshold)", `${lowStock.length} items`],
        ["Out of Stock Items (Zero Units Available)", `${outOfStock.length} items`],
        ["Expiring Soon (Next 90 Days)", `${expiringSoonProducts.length} items`],
        ["Expired Items (Action Required)", `${expiredProducts.length} items`]
      ],
      theme: "grid",
      headStyles: { fillColor: [15, 23, 42] }
    })

    // Critical Risks Table (Listing out of stock, low stock, expired, expiring)
    doc.setFont("helvetica", "bold")
    doc.setFontSize(12)
    doc.text("Itemized Inventory Risk & Expiry Logs", 14, doc.lastAutoTable.finalY + 12)

    const alertRows = []
    outOfStock.forEach(p => alertRows.push([p.name, "0 units", "OUT OF STOCK", "Immediate reorder critical"]))
    lowStock.forEach(p => alertRows.push([p.name, `${p.stock} units`, "LOW STOCK", "Reorder pipeline advised"]))
    expiredProducts.forEach(p => alertRows.push([p.name, `${p.stock} units`, "EXPIRED", "Purge from retail shelf"]))
    expiringSoonProducts.forEach(p => {
      const dateVal = p.expiryDate || (Array.isArray(p.variants) && p.variants[0]?.expiryDate) || "N/A"
      alertRows.push([p.name, `${p.stock} units`, "EXPIRING SOON", `Expires on: ${dateVal}`])
    })

    autoTable(doc, {
      startY: doc.lastAutoTable.finalY + 16,
      head: [["Product Name", "Current Stock Status", "Risk Category", "Resolution Details"]],
      body: alertRows.length ? alertRows : [["No critical stock or shelf-life alerts present.", "-", "-", "-"]],
      theme: "striped",
      headStyles: { fillColor: [220, 38, 38] }
    })

    // Today's Sales Breakdown Table
    doc.setFont("helvetica", "bold")
    doc.setFontSize(12)
    doc.text("Sales Made Today", 14, doc.lastAutoTable.finalY + 12)

    const tableRows = todaySales.map(sale => [
      sale.name,
      sale.sellQuantity ?? sale.quantity,
      // FIX: Parentheses added to handle the operational parsing logic smoothly here too
      "NGN " + (Number(sale.price) * Number(sale.sellQuantity ?? sale.quantity)).toLocaleString(),
      sale.date.split(",")[1] || sale.date
    ])

    autoTable(doc, {
      startY: doc.lastAutoTable.finalY + 16,
      head: [["Product Name", "Quantity Sold", "Total Price", "Time of Sale"]],
      body: tableRows.length ? tableRows : [["No sales recorded today.", "-", "-", "-"]],
      theme: "striped",
      headStyles: { fillColor: [79, 70, 229] }
    })

    // Brand Signature Footer placement
    const finalY = doc.lastAutoTable.finalY + 25
    doc.setFont("helvetica", "italic")
    doc.setFontSize(10)
    doc.setTextColor(100)
    doc.text("Generated by Tipia", 14, finalY < 280 ? finalY : 280)

    doc.save(`Tipia_Demo_Report_${todayString}.pdf`)
  }

  return (
    <div className="reports-page">
      
      {/* HEADER ROW */}
      <div className="reports-header">
        <div className="reports-title">
          <BarChart3 size={22} className="reports-icon-accent" />
          <div>
            <h2>Tipia Demo Reports</h2>
            <p>Today's system stock levels, shelf tracking profiles, and sales analytics</p>
          </div>
        </div>

        <div className="reports-actions">
          <button onClick={downloadPDF} className="download-btn">
            <FileDown size={16} /> PDF Export
          </button>
          <button onClick={downloadReportText} className="download-btn secondary">
            TXT Download
          </button>
          <button onClick={shareToWhatsApp} className="whatsapp-btn">
            <MessageCircle size={16} /> WhatsApp Share
          </button>
        </div>
      </div>

      {/* DASHBOARD PREVIEW SHELL */}
      <div className="report-card">
        
        {/* FINANCIAL SUMMARY BOXES */}
        <div className="report-grid">
          <div className="report-box report-summary-box">
            <div className="report-box-meta">
              <Package size={16} />
              <p>Total Products We Have</p>
            </div>
            <h2>{totalProducts} Items</h2>
          </div>

          <div className="report-box report-summary-box">
            <div className="report-box-meta report-box-meta-accent">
              <Clock size={16} />
              <p>Sales Revenue Made Today</p>
            </div>
            <h2 className="report-value-highlight">₦{todayRevenue.toLocaleString()}</h2>
          </div>
        </div>

        {/* ANALYTICS SPLIT SECTIONS */}
        <div className="report-details-split-grid">
          
          {/* TRACKING TIMELINE BLOCK */}
          <div className="report-section report-section-panel">
            <div className="section-title-wrapper">
              <Clock size={16} />
              <h3>Sales Made Today & Time Occurred</h3>
            </div>
            <div className="nested-scrolling-alert-list">
              {todaySales.length > 0 ? (
                todaySales.map((sale, i) => (
                  <div key={i} className="report-item report-item-row">
                    <span>{sale.name} ({(sale.sellQuantity ?? sale.quantity)} sold)</span>
                    <strong>{sale.date.split(',')[1] || sale.date}</strong>
                  </div>
                ))
              ) : (
                <p className="report-empty-text">No sales have been recorded yet today.</p>
              )}
            </div>
          </div>

          {/* DYNAMIC ALERT TRACKERS BLOCK */}
          <div className="report-section report-section-panel report-section-column">
            
            {/* Stock Levels Status Indicators */}
            <div className="status-panel">
              <h3>Stock & Expiration Alerts</h3>
              <div className="report-status-summary-row" style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '8px' }}>
                <div className="status-micro-pill red-pill">
                  <span>Out of Stock</span>
                  <strong>{outOfStock.length} items</strong>
                </div>
                <div className="status-micro-pill amber-pill">
                  <span>Low Stock</span>
                  <strong>{lowStock.length} items</strong>
                </div>
                <div className="status-micro-pill amber-pill" style={{ background: '#fef3c7', color: '#d97706', borderColor: '#fcd34d' }}>
                  <span>Expiring Soon</span>
                  <strong>{expiringSoonProducts.length} items</strong>
                </div>
                <div className="status-micro-pill red-pill" style={{ background: '#fee2e2', color: '#dc2626', borderColor: '#fca5a5' }}>
                  <span>Expired</span>
                  <strong>{expiredProducts.length} items</strong>
                </div>
              </div>
            </div>

            {/* Premium Ranking Block for Top Items */}
            {computedTopProducts.length > 0 && (
              <div className="status-panel">
                <h3>Today's Top High-Grossing Products</h3>
                <div className="top-products-list">
                  {computedTopProducts.map((p, idx) => (
                    <div key={idx} className="top-product-item">
                      <span className="top-product-rank">{idx + 1}</span>
                      <span className="top-product-name">{p.name}</span>
                      <span className="top-product-value">₦{p.revenue.toLocaleString()}</span>
                    </div>
                  ))}
                </div>
              </div>
            )}

          </div>

        </div>

      </div>
    </div>
  )
}

export default Reports